# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
pygments: true

# Title
name: API Program
subtitle: A comprehensive solution for agencies.  

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/api-program'

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: http://18f.github.io/api-program/assets/img/18f-logo.png
logoalt: 18f logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Program Components
  url: program-components
  internal: true
- text: Program Planning
  url: https://github.com/18F/api-program/milestones/Initial%20Program%20Planning
  internal: false
- text: User Stories
  url: user-stories
  internal: true
- text: Frequently Asked Questions
  url: faq
  internal: true
- text: Get In Touch
  url: contact
  internal: true
- text: Program Feedback
  url: https://github.com/18F/API-Program/issues
  internal: false


# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: API Program
  description: Main repository
  url: https://github.com/18F/API-Program

# Style Variables
brand_color: "#1188ff"
