# Base configuration
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- program-planning
- proposal

markdown: redcarpet
highlighter: rouge

# Title
name: API Program
subtitle: A comprehensive solution for agencies.  

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18f logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Agency API
  url: agency-api/
  internal: true
- text: Developer Hub
  url: developer-hub/
  internal: true
- text: API Program
  url: program-components/
  internal: true
- text: Engagement
  url: engagement/
  internal: true
- text: Agency Manual
  url: agency-manual/
  internal: true
- text: 18F Manual
  url: 18f-manual/
  internal: true
- text: Program Planning
  url: program-planning/
  internal: true
- text: Get in Touch
  url: contact/
  internal: true
- text: Program Odds and Ends
  url: alternative-list-of-deliverables/
  internal: true
- text: FAQ
  url: faq/
  internal: true
- text: Getting Started
  url: getting-started/
  internal: true
- text: User Stories
  url: user-stories/
  internal: true

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: API Program
  description: Main repository
  url: https://github.com/18F/API-Program

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

google_analytics_ua: UA-48605964-19

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
