# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
pygments: true

# Title
name: API Program
subtitle: A comprehensive solution for agencies.  

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/api-program'

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: https://pages.18f.gov/api-program/assets/img/18f-logo.png
logoalt: 18f logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Overview
  url: https://pages.18f.gov/api-program/
  internal: false
- text: --Agency API 
  url: https://pages.18f.gov/api-program/agency-api/
  internal: false
- text: --Developer Hub
  url: https://pages.18f.gov/api-program/developer-hub/
  internal: false
- text: --Agency Training
  url: https://pages.18f.gov/api-program/training/ 
  internal: false
- text: --API Analytics
  url: https://pages.18f.gov/api-program/api-analytics/
  internal: false
- text: Developer Engagement
  url: https://pages.18f.gov/api-program/engagement/
  internal: false
- text: How to Get Started
  url: https://pages.18f.gov/api-program/process/
  internal: false
- text: --Project Outline
  url: https://pages.18f.gov/api-program/project-outline/
  internal: false
- text: --Statement of Work
  url: https://pages.18f.gov/api-program/sow/
  internal: false
- text: Agency Manual
  url: https://pages.18f.gov/api-program/agency-manual/
  internal: false
- text: 18F Manual
  url: https://pages.18f.gov/api-program/18f-manual/
  internal: false
- text: Get In Touch
  url: https://pages.18f.gov/api-program/contact/
  internal: false


# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: API Program
  description: Main repository
  url: https://github.com/18F/API-Program

# Style Variables
brand_color: "#1188ff"
